using System.Text.RegularExpressions;
using Aegis.Architecture.Diagnostics;
using Aegis.Shared.Architecture.Enums;
using Aegis.Shared.Architecture.Models;
using Aegis.Shared.Architecture.Models.Policies;
using Aegis.Shared.Architecture.Models.Policies.Architecture;
using Aegis.Shared.Diagnostics;
using Franz.Common.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Aegis.Architecture.Evaluators.Architecture;

/// <summary>
/// Evaluates Node.js and TypeScript backend architecture practices.
///
/// This evaluator consumes ProjectArchitectureContext generated by detectors.
/// It does not rediscover frameworks, dependencies, or project structure.
///
/// Responsibilities:
/// - Node runtime security patterns
/// - Module system consistency
/// - Async usage risks
/// - Backend-specific code quality indicators
///
/// Discovery responsibility belongs to detectors.
/// Rule interpretation belongs to the RuleEngine.
/// </summary>
public sealed class NodeEvaluator
    : BaseArchitectureEvaluator, IScopedDependency
{
    private readonly NodePolicy _policy;


    public override string Name =>
        "NodeEvaluator";


    public override string[] SupportedLanguages =>
    [
        "JavaScript",
        "TypeScript"
    ];


    public override string[] SupportedFrameworks =>
    [
        "Node",
        "NestJS",
        "Next.js"
    ];


    private static readonly Regex EvalRegex =
        new(
            @"\beval\s*\(",
            RegexOptions.Compiled);


    private static readonly Regex ChildProcessRegex =
        new(
            @"(?:require\s*\(\s*['""]child_process['""]\s*\)|from\s+['""]child_process['""])",
            RegexOptions.Compiled);


    private static readonly Regex CallbackRegex =
        new(
            @"function\s*\([^)]*\)\s*\{[^{}]*(function\s*\([^)]*\)\s*\{){3,}",
            RegexOptions.Compiled);


    private static readonly Regex AsyncFunctionRegex =
        new(
            @"\basync\s+(function|\()",
            RegexOptions.Compiled);


    private static readonly Regex RequireRegex =
        new(
            @"\brequire\s*\(",
            RegexOptions.Compiled);


    public NodeEvaluator(
        ILogger<NodeEvaluator> logger,
        IOptions<AegisArchitecturePolicy> options)
        : base(logger)
    {
        _policy =
            options.Value.Node
            ?? new NodePolicy();
    }



    protected override async Task<IEnumerable<ArchitectureEvaluatorResult>>
        EvaluateCoreAsync(
            string projectPath,
            CancellationToken token)
    {
        var results =
            new List<ArchitectureEvaluatorResult>();


        if (Context is null)
            return results;


        if (!IsSupportedNodeProject(Context))
        {
            AegisDiagnostics.Report(
                Name,
                DiagnosticLevel.Trace,
                "Skipping Node evaluation. Unsupported project context.");

            return results;
        }


        var files =
            ResolveSourceFiles(
                projectPath,
                Context.Language == "TypeScript"
                    ? ".ts"
                    : ".js",
                ".mjs",
                ".cjs");


        if (files.Count == 0)
            return results;


        AegisDiagnostics.Report(
            Name,
            DiagnosticLevel.Trace,
            $"Evaluating {files.Count} Node files.");


        foreach (var file in files)
        {
            token.ThrowIfCancellationRequested();


            if (IsGeneratedOrExcluded(file))
                continue;


            var content =
                await File.ReadAllTextAsync(
                    file,
                    token);


            EvaluateSecurityPatterns(
                file,
                content,
                results);

            EvaluateAsyncPatterns(
                file,
                content,
                results);

            EvaluateModuleSystem(
                file,
                content,
                results);
        }


        AegisDiagnostics.Report(
            Name,
            DiagnosticLevel.Info,
            $"Node evaluation completed with {results.Count} violation(s).");


        return results;
    }



    private void EvaluateSecurityPatterns(
        string file,
        string content,
        List<ArchitectureEvaluatorResult> results)
    {
        if (_policy.DisallowEval &&
            EvalRegex.IsMatch(content))
        {
            results.Add(
                CreateViolation(
                    file,
                    "NODE001",
                    "Dynamic eval execution detected.",
                    "Security"));
        }


        if (_policy.DisallowChildProcess &&
            ChildProcessRegex.IsMatch(content))
        {
            results.Add(
                CreateViolation(
                    file,
                    "NODE002",
                    "Direct child_process usage detected.",
                    "Security"));
        }


        if (CallbackRegex.IsMatch(content))
        {
            results.Add(
                CreateViolation(
                    file,
                    "NODE003",
                    "Deep callback nesting detected.",
                    "Maintainability"));
        }
    }



    private void EvaluateAsyncPatterns(
        string file,
        string content,
        List<ArchitectureEvaluatorResult> results)
    {
        if (!_policy.CheckUnhandledPromises)
            return;


        if (!AsyncFunctionRegex.IsMatch(content))
            return;


        if (content.Contains(
                ".catch",
                StringComparison.OrdinalIgnoreCase))
        {
            return;
        }


        results.Add(
            CreateViolation(
                file,
                "NODE004",
                "Async execution pattern without visible error handling.",
                "Reliability"));
    }



    private void EvaluateModuleSystem(
        string file,
        string content,
        List<ArchitectureEvaluatorResult> results)
    {
        if (!_policy.EnforceESModules)
            return;


        if (!RequireRegex.IsMatch(content))
            return;


        var usesEsm =
            Context?.PatternsDetected.Any(
                x =>
                    x.Equals(
                        "ESModule",
                        StringComparison.OrdinalIgnoreCase))
            == true;


        if (!usesEsm)
            return;


        results.Add(
            CreateViolation(
                file,
                "NODE005",
                "CommonJS require detected in ES Module project.",
                "Architecture"));
    }



    private ArchitectureEvaluatorResult CreateViolation(
        string file,
        string rule,
        string message,
        string category)
    {
        var result =
            CreateResult(
                file,
                nameof(ArchitectureRuleCategory.Architecture));


        result.Metrics["Violation"] = 1;
        result.Metrics["ArchitectureCompliance"] = 0;


        result.Metadata["Rule"] = rule;
        result.Metadata["Message"] = message;
        result.Metadata["Category"] = category;
        result.Metadata["Language"] =
            Context?.Language ?? "Unknown";
        result.Metadata["Framework"] =
            Context?.Framework ?? "Unknown";
        result.Metadata["Layer"] =
            ResolveLayer(file) ?? "Unknown";


        return result;
    }



    private static bool IsSupportedNodeProject(
        ProjectArchitectureContext context)
    {
        return
            context.Language is
            "JavaScript" or "TypeScript"
            &&
            (
                context.Framework?.Contains(
                    "Node",
                    StringComparison.OrdinalIgnoreCase) == true
                ||
                context.Framework?.Contains(
                    "Nest",
                    StringComparison.OrdinalIgnoreCase) == true
                ||
                context.Framework?.Contains(
                    "Next",
                    StringComparison.OrdinalIgnoreCase) == true
            );
    }



    private string? ResolveLayer(
        string file)
    {
        return Context?
            .Layers
            .FirstOrDefault(
                layer =>
                    layer.Files.Contains(
                        file,
                        StringComparer.OrdinalIgnoreCase))
            ?.Name;
    }



    private static bool IsGeneratedOrExcluded(
        string file)
    {
        return
            file.Contains(
                "generated",
                StringComparison.OrdinalIgnoreCase)
            ||
            file.Contains(
                "node_modules",
                StringComparison.OrdinalIgnoreCase);
    }
}