<Project Sdk="Microsoft.NET.Sdk">



  <ItemGroup>
    <Folder Include="Diagnostics\" />
  </ItemGroup>
  
  <PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  
  

  <ItemGroup>
    <PackageReference Include="Franz.Common.DependencyInjection" Version="1.6.21" />
    <PackageReference Include="Franz.Common.Logging" Version="1.6.21" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
    
      <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
      <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
      <PackageReference Include="System.ServiceModel.NetTcp" Version="10.0.652802" />
      <PackageReference Include="System.Web.Services.Description" Version="10.0.652802" />
   
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aegis.Infrastructure\Aegis.Infrastructure.csproj" />
    <ProjectReference Include="..\Aegis.Shared\Aegis.Shared.csproj" />
  </ItemGroup>

</Project>
