<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Franz.Common.Logging" Version="1.6.21" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0" />
  </ItemGroup>
  
  


  <ItemGroup>
    <ProjectReference Include="..\Aegis.Infrastructure\Aegis.Infrastructure.csproj" />
    <ProjectReference Include="..\Aegis.Sdk\Aegis.Sdk.csproj" />
  </ItemGroup>

</Project>
