using Aegis.Shared.Security.Enums;

namespace Aegis.Shared.Security.Models;

/// <summary>
/// Immutable atomic evidence unit generated by a probe. 
/// Never mutated or exposed beyond its containing evaluator.
/// </summary>
public record SecuritySignal
{
    public Guid SignalId { get; init; } = Guid.NewGuid();

    /// <summary>Logical category (Network, Application, IaC, etc.).</summary>
    public string Category { get; init; } = string.Empty;

    /// <summary>Stable identifier of the producing probe.</summary>
    public string DetectorId { get; init; } = string.Empty;

    public SecuritySeverity Severity { get; init; } = SecuritySeverity.Info;
    public double Score { get; init; } = 0.0;

    /// <summary>Human-readable short description of the finding.</summary>
    public string Evidence { get; init; } = string.Empty;

    /// <summary>Optional extra context, always serializable.</summary>
    public IReadOnlyDictionary<string, object>? Metadata { get; init; }

    public DateTimeOffset TimestampUtc { get; init; } = DateTimeOffset.UtcNow;

    public override string ToString() =>
        $"{TimestampUtc:u} [{Category}] {DetectorId} {Severity} ({Score:F2}) — {Evidence}";
}
