using Aegis.Shared.Models;

namespace Aegis.Shared.Contracts;

/// <summary>
/// Contract for all Aegis Evaluators.
/// Evaluators analyze source code and produce structured metrics or facts (EvaluatorResults)
/// that are later interpreted by the RuleEngine.
/// </summary>
public interface IEvaluator
{
    /// <summary>
    /// Unique evaluator name (e.g., "ComplexityEvaluator", "ApiConsistencyEvaluator").
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Programming languages supported by this evaluator (e.g., ["CSharp", "TypeScript"]).
    /// </summary>
    string[] SupportedLanguages { get; }

    /// <summary>
    /// Frameworks supported by this evaluator (e.g., ["ASP.NET", "Spring", "FastAPI"]).
    /// </summary>
    string[] SupportedFrameworks { get; }

    /// <summary>
    /// Executes the evaluator on the given project using the provided contextual information.
    /// Produces structured <see cref="EvaluatorResult"/> data, not direct rule evaluations.
    /// </summary>
    /// <param name="projectPath">Path to the project root.</param>
    /// <param name="context">Detected project context (language, framework, metadata).</param>
    /// <param name="token">Optional cancellation token.</param>
    /// <returns>Collection of <see cref="EvaluatorResult"/> metrics generated by the evaluator.</returns>
    Task<IEnumerable<EvaluatorResult>> EvaluateAsync(
        string projectPath,
        ProjectContext context,
        CancellationToken token = default);
}
