using Aegis.Shared.Architecture.Models;

using CommunityToolkit.Mvvm.ComponentModel;

using LiveChartsCore;
using LiveChartsCore.SkiaSharpView;
using LiveChartsCore.SkiaSharpView.Painting;

using Microsoft.Extensions.Logging;

using SkiaSharp;

using System.Collections.ObjectModel;


namespace Aegis.Wpf.ViewModels;

public sealed partial class LayerDashboardViewModel : ObservableObject
{
    private readonly ILogger<LayerDashboardViewModel> _logger;



    public LayerDashboardViewModel(
        ILogger<LayerDashboardViewModel> logger)
    {
        _logger = logger;

        Layers =
            new ObservableCollection<LayerDashboardItem>();

        Series =
            new ObservableCollection<ISeries>();
    }



    // ==========================================================
    // STATE
    // ==========================================================

    public ObservableCollection<LayerDashboardItem> Layers
    {
        get;
    }


    public ObservableCollection<ISeries> Series
    {
        get;
    }



    [ObservableProperty]
    private Axis[] xAxes = [];



    [ObservableProperty]
    private Axis[] yAxes = [];



    // ==========================================================
    // KPI
    // ==========================================================

    [ObservableProperty]
    private int totalLayers;



    [ObservableProperty]
    private int totalViolations;



    [ObservableProperty]
    private string dominantLayer = "-";



    [ObservableProperty]
    private double averageViolationsPerLayer;



    [ObservableProperty]
    private double averageHealth;



    // ==========================================================
    // UPDATE FROM REPORT
    // ==========================================================

    public void Update(
        AegisArchitectureReport report)
    {
        try
        {
            Layers.Clear();



            /*
             * Domain summaries are generated by
             * CrossEvaluatorAggregator.
             *
             * No grouping or counting happens here.
             */


            foreach (var domain in report.Domains
                         .OrderByDescending(x => x.Violations))
            {
                Layers.Add(
                    new LayerDashboardItem(
                        domain.Domain,
                        domain.RulesEvaluated,
                        domain.Violations,
                        domain.HealthIndex,
                        domain.WeightedScore));
            }



            TotalLayers =
                Layers.Count;



            TotalViolations =
                Layers.Sum(x =>
                    x.Violations);



            DominantLayer =
                Layers
                    .OrderByDescending(x =>
                        x.Violations)
                    .FirstOrDefault()
                    ?.Layer
                ?? "-";



            AverageViolationsPerLayer =
                TotalLayers == 0
                    ? 0
                    : (double)TotalViolations /
                      TotalLayers;



            AverageHealth =
                Layers.Count == 0
                    ? 100
                    : Layers.Average(x =>
                        x.Health*10);



            BuildChart();



            _logger.LogInformation(
                "Layer dashboard updated from report ({Count} domains).",
                TotalLayers);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Failed updating layer dashboard.");
        }
    }



    // ==========================================================
    // CHART
    // ==========================================================

    private void BuildChart()
    {
        var ordered =
            Layers
                .OrderByDescending(x =>
                    x.Violations)
                .ToList();



        if (ordered.Count == 0)
        {
            Series.Clear();

            XAxes = [];

            YAxes = [];

            return;
        }



        Series.Clear();



        Series.Add(
            new ColumnSeries<int>
            {
                Name =
                    "Violations",

                Values =
                    ordered
                        .Select(x =>
                            x.Violations)
                        .ToArray(),

                Fill =
                    new SolidColorPaint(
                        SKColors.DeepSkyBlue)
            });



        XAxes =
        [
            new Axis
            {
                Labels =
                    ordered
                        .Select(x =>
                            x.Layer)
                        .ToArray(),

                LabelsRotation = 15
            }
        ];



        YAxes =
        [
            new Axis
            {
                Name =
                    "Violations"
            }
        ];
    }
}



public sealed record LayerDashboardItem(
    string Layer,
    int RulesEvaluated,
    int Violations,
    double Health,
    double Compliance);