using Aegis.Architecture.Aggregation;
using Aegis.Architecture.Scoring;
using Aegis.Shared.Architecture.Models;
using Aegis.Shared.Architecture.Models.Policies;
using Aegis.Shared.Contracts;

using Microsoft.Extensions.Logging;

namespace Aegis.Architecture.RuleEngines;

/// <summary>
/// Orchestrates the Aegis analysis pipeline.
///
/// Pipeline:
/// ProjectArchitectureContext
///         ↓
/// Evaluators
///         ↓
/// ArchitectureEvaluatorResult (facts)
///         ↓
/// RuleEngineCore
///         ↓
/// ArchitectureRuleresult
///         ↓
/// RuleWeightingEngine
///         ↓
/// CrossEvaluatorAggregator
///         ↓
/// AegisArchitectureReport
///
/// Evaluators never apply policy.
/// They only consume detected context and produce facts.
/// </summary>
public sealed class RuleEngine
{
    private readonly IReadOnlyCollection<IEvaluator> _evaluators;

    private readonly RuleEngineCore _core;

    private readonly RuleWeightingEngine _weighting;

    private readonly CrossEvaluatorAggregator _aggregator;

    private readonly ILogger<RuleEngine> _logger;



    public RuleEngine(
        IEnumerable<IEvaluator> evaluators,
        RuleEngineCore core,
        RuleWeightingEngine weighting,
        CrossEvaluatorAggregator aggregator,
        ILogger<RuleEngine> logger)
    {
        _evaluators =
            evaluators.ToArray();

        _core = core;
        _weighting = weighting;
        _aggregator = aggregator;
        _logger = logger;
    }



    /// <summary>
    /// Applies policy only to rule interpretation,
    /// weighting and aggregation.
    /// </summary>
    public void ApplyPolicy(
        AegisArchitecturePolicy policy)
    {
        _core.ApplyPolicy(policy);

        _weighting.ApplyPolicy(policy);

        _aggregator.ApplyPolicy(policy);


        _logger.LogInformation(
            "Aegis policy applied. Version={Version}",
            policy.Version ?? "Unknown");
    }



    /// <summary>
    /// Executes the full architecture analysis pipeline.
    /// </summary>
    public async Task<AegisArchitectureReport> RunAsync(
        string projectPath,
        ProjectArchitectureContext context,
        CancellationToken token = default,
        Func<string, bool>? pathFilter = null)
    {
        _logger.LogInformation(
            "Starting Aegis scan for {Project}",
            context.ProjectName);



        var facts =
            new List<ArchitectureEvaluatorResult>();



        foreach (var evaluator in _evaluators)
        {
            token.ThrowIfCancellationRequested();



            if (!SupportsContext(
                    evaluator,
                    context))
            {
                continue;
            }



            try
            {
                var results =
                    await evaluator.EvaluateAsync(
                        projectPath,
                        context,
                        token);



                foreach (var result in results)
                {
                    token.ThrowIfCancellationRequested();



                    if (pathFilter is not null &&
                       !pathFilter(result.Target))
                    {
                        continue;
                    }



                    facts.Add(result);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(
                    ex,
                    "Evaluator {Evaluator} failed.",
                    evaluator.Name);
            }
        }



        _logger.LogInformation(
            "{Count} facts generated by evaluators.",
            facts.Count);



        var ruleResults =
            _core
                .Evaluate(
                    context,
                    facts)
                .ToList();



        var weightedResults =
            _weighting
                .ApplyWeights(
                    ruleResults)
                .ToList();



        var report =
            _aggregator.Aggregate(
                weightedResults,
                facts,
                context);



        _logger.LogInformation(
            "Aegis scan completed. Violations={Violations}",
            report.TotalViolations);



        return report;
    }



    private static bool SupportsContext(
        IEvaluator evaluator,
        ProjectArchitectureContext context)
    {
        var languageSupported =
            evaluator.SupportedLanguages.Contains(
                context.Language,
                StringComparer.OrdinalIgnoreCase)
            ||
            evaluator.SupportedLanguages.Contains("*");



        if (!languageSupported)
            return false;



        if (string.IsNullOrWhiteSpace(
            context.Framework))
        {
            return true;
        }



        return evaluator.SupportedFrameworks.Contains(
                    context.Framework,
                    StringComparer.OrdinalIgnoreCase)
               ||
               evaluator.SupportedFrameworks.Contains("*");
    }
}