using Aegis.Architecture.Aggregation;
using Aegis.Architecture.Scoring;
using Aegis.Shared.Architecture.Models;
using Aegis.Shared.Architecture.Models.Policies;
using Aegis.Shared.Contracts;

using Microsoft.Extensions.Logging;

namespace Aegis.Architecture.RuleEngines;

/// <summary>
/// Orchestrates the complete Aegis analysis pipeline.
///
/// Pipeline:
/// ProjectArchitectureContext
///         ↓
/// Evaluators
///         ↓
/// ArchitectureEvaluatorResult (facts)
///         ↓
/// RuleEngineCore
///         ↓
/// ArchitectureRuleResult
///         ↓
/// RuleWeightingEngine
///         ↓
/// CrossEvaluatorAggregator
///         ↓
/// AegisArchitectureReport
///
/// Policy ownership:
/// - Evaluators receive enablement/weight policies.
/// - RuleEngineCore receives rule interpretation policies.
/// - RuleWeightingEngine receives scoring policies.
/// - CrossEvaluatorAggregator receives aggregation policies.
/// </summary>
public sealed class RuleEngine
{
    private readonly IReadOnlyCollection<IEvaluator> _evaluators;

    private readonly RuleEngineCore _core;

    private readonly RuleWeightingEngine _weighting;

    private readonly CrossEvaluatorAggregator _aggregator;

    private readonly ILogger<RuleEngine> _logger;



    public RuleEngine(
        IEnumerable<IEvaluator> evaluators,
        RuleEngineCore core,
        RuleWeightingEngine weighting,
        CrossEvaluatorAggregator aggregator,
        ILogger<RuleEngine> logger)
    {
        _evaluators =
            evaluators.ToArray();

        _core = core;
        _weighting = weighting;
        _aggregator = aggregator;
        _logger = logger;


        foreach (var evaluator in _evaluators)
        {
            _logger.LogInformation(
                "Registered evaluator: {Evaluator}",
                evaluator.Name);
        }


        _logger.LogInformation(
            "Aegis RuleEngine initialized with {Count} evaluators.",
            _evaluators.Count);
    }



    /// <summary>
    /// Applies policy to the complete analysis pipeline.
    /// </summary>
    public void ApplyPolicy(
        AegisArchitecturePolicy policy)
    {
        ArgumentNullException.ThrowIfNull(policy);


        _core.ApplyPolicy(policy);

        _weighting.ApplyPolicy(policy);

        _aggregator.ApplyPolicy(policy);
                         

        _logger.LogInformation(
            "Aegis policy applied. Version={Version}. Evaluators={Count}",
            policy.Version ?? "Unknown",
            _evaluators.Count);
    }



    /// <summary>
    /// Executes the full architecture analysis pipeline.
    /// </summary>
    public async Task<AegisArchitectureReport> RunAsync(
        string projectPath,
        ProjectArchitectureContext context,
        CancellationToken token = default,
        Func<string, bool>? pathFilter = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(projectPath);

        ArgumentNullException.ThrowIfNull(context);


        _logger.LogInformation(
            "Starting Aegis scan for {Project}",
            context.ProjectName);



        var facts =
            new List<ArchitectureEvaluatorResult>();



        foreach (var evaluator in _evaluators)
        {
            token.ThrowIfCancellationRequested();



            if (!SupportsContext(
                    evaluator,
                    context))
            {
                _logger.LogDebug(
                    "Evaluator {Evaluator} skipped. Context not supported: {Language}/{Framework}",
                    evaluator.Name,
                    context.Language,
                    context.Framework);

                continue;
            }



            _logger.LogDebug(
                "Executing evaluator {Evaluator}",
                evaluator.Name);



            try
            {
                var results =
                    await evaluator.EvaluateAsync(
                        projectPath,
                        context,
                        token);



                foreach (var result in results)
                {
                    token.ThrowIfCancellationRequested();


                    if (pathFilter is not null &&
                        !pathFilter(result.Target))
                    {
                        continue;
                    }


                    facts.Add(result);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(
                    ex,
                    "Evaluator {Evaluator} failed.",
                    evaluator.Name);
            }
        }



        _logger.LogInformation(
            "{Count} facts generated by {EvaluatorCount} evaluators.",
            facts.Count,
            _evaluators.Count);



        var ruleResults =
            _core
                .Evaluate(
                    context,
                    facts)
                .ToList();



        _logger.LogInformation(
            "{Count} rule violations generated.",
            ruleResults.Count);



        var weightedResults =
            _weighting
                .ApplyWeights(ruleResults)
                .ToList();



        var report =
            _aggregator.Aggregate(
                weightedResults,
                facts,
                context);



        _logger.LogInformation(
            "Aegis scan completed. Violations={Violations}",
            report.TotalViolations);



        return report;
    }



    private static bool SupportsContext(
        IEvaluator evaluator,
        ProjectArchitectureContext context)
    {
        if (!SupportsLanguage(
                evaluator,
                context.Language))
        {
            return false;
        }



        return SupportsFramework(
            evaluator,
            context.Framework);
    }



    private static bool SupportsLanguage(
        IEvaluator evaluator,
        string language)
    {
        return evaluator.SupportedLanguages.Contains(
                   "*",
                   StringComparer.OrdinalIgnoreCase)
               ||
               evaluator.SupportedLanguages.Contains(
                   language,
                   StringComparer.OrdinalIgnoreCase);
    }



    private static bool SupportsFramework(
        IEvaluator evaluator,
        string? framework)
    {
        if (evaluator.SupportedFrameworks.Contains(
                "*",
                StringComparer.OrdinalIgnoreCase))
        {
            return true;
        }



        if (evaluator.SupportedFrameworks.Contains(
                "LanguageAgnostic",
                StringComparer.OrdinalIgnoreCase))
        {
            return true;
        }



        if (string.IsNullOrWhiteSpace(framework))
        {
            return true;
        }



        foreach (var supported in evaluator.SupportedFrameworks)
        {
            if (framework.Equals(
                    supported,
                    StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }



            if (IsDotNetFamily(framework) &&
                IsDotNetFamily(supported))
            {
                return true;
            }



            if (framework.Contains(
                    "ASP.NET",
                    StringComparison.OrdinalIgnoreCase)
                &&
                supported.Contains(
                    "ASP.NET",
                    StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }



        return false;
    }



    private static bool IsDotNetFamily(
        string framework)
    {
        return framework.Contains(
                   ".NET",
                   StringComparison.OrdinalIgnoreCase)
               ||
               framework.Contains(
                   "EF Core",
                   StringComparison.OrdinalIgnoreCase)
               ||
               framework.Contains(
                   "ASP.NET",
                   StringComparison.OrdinalIgnoreCase);
    }
}