using System.Text.RegularExpressions;
using Aegis.Architecture.Diagnostics;
using Aegis.Shared.Architecture.Enums;
using Aegis.Shared.Architecture.Models;
using Aegis.Shared.Architecture.Models.Policies;
using Aegis.Shared.Architecture.Models.Policies.BackEnd;
using Aegis.Shared.Diagnostics;
using Franz.Common.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Aegis.Architecture.Evaluators.BackEnd;

/// <summary>
/// Evaluates class cohesion by analyzing member distribution
/// inside detected source types.
///
/// The evaluator consumes architectural context generated by detectors.
/// It reports only cohesion violations based on configured policy.
///
/// Discovery responsibility belongs to detectors.
/// Rule interpretation belongs to the RuleEngine.
/// </summary>
public sealed class CohesionEvaluator
    : BaseArchitectureEvaluator, IScopedDependency
{
    private readonly CohesionPolicy _policy;


    public override string Name =>
        "CohesionEvaluator";


    public override string[] SupportedLanguages =>
    [
        "C#",
        "Java",
        "Python"
    ];


    public override string[] SupportedFrameworks =>
    [
        "ASP.NET",
        "Spring Boot",
        "FastAPI"
    ];



    private static readonly Regex ClassRegex =
        new(
            @"\bclass\s+([A-Za-z_][A-Za-z0-9_]*)",
            RegexOptions.Compiled);



    public CohesionEvaluator(
        ILogger<CohesionEvaluator> logger,
        IOptions<AegisArchitecturePolicy> options)
        : base(logger)
    {
        _policy =
            options.Value.Cohesion
            ?? new CohesionPolicy();
    }



    protected override async Task<IEnumerable<ArchitectureEvaluatorResult>>
        EvaluateCoreAsync(
            string projectPath,
            CancellationToken token)
    {
        var results =
            new List<ArchitectureEvaluatorResult>();


        if (Context is null)
            return results;



        var files =
            ResolveSourceFiles(
                projectPath,
                GetExtensions(Context.Language));


        if (files.Count == 0)
        {
            AegisDiagnostics.Report(
                Name,
                DiagnosticLevel.Trace,
                "No source files found for cohesion analysis.");

            return results;
        }



        AegisDiagnostics.Report(
            Name,
            DiagnosticLevel.Trace,
            $"Analyzing cohesion for {files.Count} files " +
            $"({Context.Language}/{Context.Framework}).");



        foreach (var file in files)
        {
            token.ThrowIfCancellationRequested();


            var content =
                await File.ReadAllTextAsync(
                    file,
                    token);



            foreach (Match match in ClassRegex.Matches(content))
            {
                token.ThrowIfCancellationRequested();


                var className =
                    match.Groups[1].Value;


                var classBlock =
                    ExtractClassBlock(
                        content,
                        match.Index);



                if (string.IsNullOrWhiteSpace(classBlock))
                    continue;



                var fieldCount =
                    CountFields(
                        classBlock);


                var methodCount =
                    CountMethods(
                        classBlock);


                var memberCount =
                    fieldCount +
                    methodCount;


                var ratio =
                    fieldCount == 0
                        ? methodCount
                        :
                        (double)methodCount /
                        fieldCount;



                var violations =
                    EvaluateViolations(
                        memberCount,
                        ratio);



                if (violations.Count == 0)
                    continue;



                results.Add(
                    CreateViolation(
                        file,
                        className,
                        fieldCount,
                        methodCount,
                        memberCount,
                        ratio,
                        violations));
            }
        }



        AegisDiagnostics.Report(
            Name,
            DiagnosticLevel.Info,
            $"Cohesion evaluation completed with {results.Count} violation(s).");



        return results;
    }



    private List<string> EvaluateViolations(
        int memberCount,
        double ratio)
    {
        var violations =
            new List<string>();


        if (memberCount >
            _policy.MaxMembersPerClass)
        {
            violations.Add(
                "COH001");
        }


        if (ratio >
            _policy.MaxMethodFieldRatio)
        {
            violations.Add(
                "COH002");
        }


        return violations;
    }



    private ArchitectureEvaluatorResult CreateViolation(
        string file,
        string className,
        int fieldCount,
        int methodCount,
        int memberCount,
        double ratio,
        IReadOnlyCollection<string> rules)
    {
        var result =
            CreateResult(
                file,
                nameof(ArchitectureRuleCategory.Architecture));


        result.Metrics["FieldCount"] =
            fieldCount;

        result.Metrics["MethodCount"] =
            methodCount;

        result.Metrics["MemberCount"] =
            memberCount;

        result.Metrics["MethodFieldRatio"] =
            ratio;

        result.Metrics["Violation"] =
            1;

        result.Metrics["CohesionCompliance"] =
            0;



        result.Metadata["ClassName"] =
            className;

        result.Metadata["Rules"] =
            string.Join(
                ",",
                rules);

        result.Metadata["MaxMembersPerClass"] =
            _policy.MaxMembersPerClass.ToString();

        result.Metadata["MaxMethodFieldRatio"] =
            _policy.MaxMethodFieldRatio.ToString();

        result.Metadata["Language"] =
            Context?.Language ?? "Unknown";

        result.Metadata["Framework"] =
            Context?.Framework ?? "Unknown";

        result.Metadata["Layer"] =
            ResolveLayer(file) ?? "Unknown";


        return result;
    }



    private static string[] GetExtensions(
        string language)
    {
        return language switch
        {
            "C#" =>
            [
                ".cs"
            ],

            "Java" =>
            [
                ".java"
            ],

            "Python" =>
            [
                ".py"
            ],

            _ =>
            []
        };
    }



    private string? ResolveLayer(
        string file)
    {
        return Context?
            .Layers
            .FirstOrDefault(
                layer =>
                    layer.Files.Contains(
                        file,
                        StringComparer.OrdinalIgnoreCase))
            ?.Name;
    }



    private static int CountFields(
        string content)
    {
        return Regex.Matches(
                content,
                @"\b(private|protected|public)\b.*?;")
            .Count;
    }



    private static int CountMethods(
        string content)
    {
        return Regex.Matches(
                content,
                @"\b(public|private|protected)\s+[\w<>,\[\]\s]+\s+\w+\s*\(")
            .Count;
    }



    private static string ExtractClassBlock(
        string content,
        int start)
    {
        var braceStart =
            content.IndexOf(
                '{',
                start);



        if (braceStart < 0)
            return string.Empty;



        var depth = 0;



        for (var i = braceStart; i < content.Length; i++)
        {
            if (content[i] == '{')
                depth++;


            if (content[i] == '}')
            {
                depth--;


                if (depth == 0)
                {
                    return content[
                        start..(i + 1)];
                }
            }
        }



        return string.Empty;
    }



    private static bool IsExcludedDir(
        string file)
    {
        return
            file.Contains(
                $"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}",
                StringComparison.OrdinalIgnoreCase)
            ||
            file.Contains(
                $"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}",
                StringComparison.OrdinalIgnoreCase)
            ||
            file.Contains(
                "Generated",
                StringComparison.OrdinalIgnoreCase)
            ||
            file.Contains(
                "Test",
                StringComparison.OrdinalIgnoreCase);
    }
}