using Aegis.Shared.Architecture.Enums;

namespace Aegis.Shared.Architecture.Models;

/// <summary>
/// 🧭 Describes the inferred architectural, technological, and structural profile
/// of a project. Generated deterministically by Aegis before evaluation.
/// 
/// This context acts as the single source of truth for evaluators:
/// language rules, framework rules, architecture rules, and layer analysis.
/// </summary>
public sealed class ProjectArchitectureContext
{
    // ===============================================================
    // 🔖 Identity
    // ===============================================================

    public string ProjectName { get; set; } = string.Empty;

    public string RootPath { get; set; } = string.Empty;


    // ===============================================================
    // 🧩 Technology Detection
    // ===============================================================

    /// <summary>
    /// Primary detected language.
    /// Examples: C#, Java, Python, TypeScript.
    /// </summary>
    public string Language { get; set; } = "Unknown";


    /// <summary>
    /// Detected primary framework.
    /// Examples:
    /// .NET 9, Spring Boot, Angular, Django
    /// </summary>
    public string? Framework { get; set; }


    public string? TargetRuntime { get; set; }


    public ArchitectureBuildSystem BuildSystem { get; set; }
        = ArchitectureBuildSystem.Unknown;


    public List<string> DetectedFrameworks { get; set; } = new();

    public List<string> DetectedDependencies { get; set; } = new();



    // ===============================================================
    // 🏗️ Structural Discovery
    // ===============================================================

    /// <summary>
    /// Detected modules/projects/packages.
    /// </summary>
    public List<ProjectModuleContext> Modules { get; set; } = new();


    /// <summary>
    /// Logical architecture layers detected.
    /// Examples:
    /// API
    /// Application
    /// Contracts
    /// Domain
    /// Infrastructure
    /// Tests
    /// </summary>
    public List<ProjectLayerContext> Layers { get; set; } = new();


    public string? EntryPointFile { get; set; }


    public bool IsMultiModule =>
        Modules.Count > 1;



    // ===============================================================
    // 🧱 Architecture Detection
    // ===============================================================

    public string? ArchitectureStyle { get; set; }

    public string? DomainType { get; set; }

    public string? Nature { get; set; }


    /// <summary>
    /// Detected architectural patterns.
    /// Examples:
    /// CQRS
    /// Repository
    /// Mediator
    /// Clean Architecture
    /// MVC
    /// </summary>
    public List<string> PatternsDetected { get; set; } = new();



    /// <summary>
    /// Detected architecture boundaries.
    /// Generated by BoundaryDetector.
    /// Used by evaluators to validate allowed architectural relations.
    /// </summary>
    public List<ArchitectureBoundaryContext> Boundaries { get; set; } = new();



    /// <summary>
    /// Detected dependency relationships between components.
    /// Generated by DependencyDetector.
    /// Evaluators consume this graph instead of discovering dependencies.
    /// </summary>
    public List<ArchitectureDependencyContext> Dependencies { get; set; } = new();



    // ===============================================================
    // 🧠 Detection Metadata
    // ===============================================================

    public double Confidence { get; set; }


    public string DetectorVersion { get; set; } = "1.4.0";


    public string DetectionStrategy { get; set; } = "Hybrid";


    public Dictionary<string, double> ConfidenceMap { get; set; }
        = new();


    public List<ArchitectureInferenceTrace> InferenceHistory { get; set; }
        = new();



    // ===============================================================
    // 📊 Project Statistics
    // ===============================================================

    public int FileCount { get; set; }

    public int LinesOfCode { get; set; }

    public double AverageComplexity { get; set; }



    // ===============================================================
    // 🌍 Environment
    // ===============================================================

    public Dictionary<string, string> MetadataMap { get; set; }
        = new();


    public bool IsDockerized =>
        MetadataMap.TryGetValue("Dockerized", out var value)
        && value == "true";


    public bool UsesKubernetes =>
        MetadataMap.TryGetValue("Kubernetes", out var value)
        && value == "true";


    public bool IsDeployable =>
        IsDockerized || UsesKubernetes;



    // ===============================================================
    // Compatibility Helpers
    // ===============================================================

    public string? Layer =>
        Layers.Count == 1
            ? Layers[0].Name
            : null;



    public ProjectArchitectureContext()
    {
    }


    public ProjectArchitectureContext(
        string language,
        string? framework,
        double confidence)
    {
        Language = language;
        Framework = framework;
        Confidence = confidence;
    }



    public override string ToString()
    {
        return
            $"{Language}/{Framework ?? "Unknown"} " +
            $"({Confidence:P0}) " +
            $"[{ArchitectureStyle ?? "Unknown"}]";
    }



    public object ToSummaryDto() =>
        new
        {
            ProjectName,
            RootPath,
            Language,
            Framework,
            TargetRuntime,
            BuildSystem = BuildSystem.ToString(),

            Modules = Modules.Count,
            Layers = Layers.Select(x => x.Name),

            ArchitectureStyle,
            PatternsDetected,

            BoundaryCount = Boundaries.Count,
            DependencyCount = Dependencies.Count,

            Confidence,
            DetectionStrategy,
            DetectorVersion
        };
}